# Generated by Django 3.2.13 on 2022-06-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tvShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_front', models.ImageField(upload_to='')),
                ('img_back', models.ImageField(upload_to='')),
                ('trailer', models.TextField()),
                ('overview', models.FloatField()),
                ('lauch_date', models.DateField()),
                ('chach_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cache')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('img_folder', models.ImageField(upload_to='')),
                ('tv_shows_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tvshows')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img_front', models.ImageField(upload_to='')),
                ('img_back', models.ImageField(upload_to='')),
                ('trailer', models.TextField()),
                ('overview', models.FloatField(max_length=3)),
                ('lauch_date', models.DateField()),
                ('chach_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cache')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('img_folder', models.ImageField(upload_to='')),
                ('season_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
            ],
        ),
    ]
