# Generated by Django 3.2.13 on 2022-06-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cache_casts_episode_movies_season_tvshows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
