# Generated by Django 3.2.13 on 2022-06-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='chach_fk',
            new_name='cache_fk',
        ),
        migrations.RenameField(
            model_name='tvshows',
            old_name='chach_fk',
            new_name='cache_fk',
        ),
    ]
