# Generated by Django 3.2.5 on 2022-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220614_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casts',
            name='picture',
            field=models.TextField(),
        ),
    ]
