# Generated by Django 3.2.5 on 2022-06-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_casts_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.JSONField()),
                ('tv_shows', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='img_folder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='img_back',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='img_front',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='img_folder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='img_back',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tvshows',
            name='img_front',
            field=models.TextField(),
        ),
    ]
