# Generated by Django 4.0.5 on 2022-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_list_image_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review_number',
            field=models.IntegerField(default=0, verbose_name='Number of reviews'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsoncache',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='jsoncache',
            name='movie',
            field=models.JSONField(verbose_name='Movies'),
        ),
        migrations.AlterField(
            model_name='jsoncache',
            name='tv_shows',
            field=models.JSONField(verbose_name='TV shows'),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(upload_to='list_images', verbose_name='List image'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, verbose_name='List name'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='count',
            field=models.IntegerField(verbose_name='Progress count'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(verbose_name='Rating value'),
        ),
        migrations.AlterField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(verbose_name='Average rating'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='content_completed',
            field=models.IntegerField(verbose_name='Content completed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=10, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Username'),
        ),
    ]
