# Generated by Django 4.0.5 on 2022-06-24 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_alter_user_managers_remove_user_email_remove_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/', verbose_name='Profile picture')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Gender')),
                ('location', models.CharField(blank=True, max_length=10, verbose_name='Location')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Language')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('content_completed', models.IntegerField(default=0, verbose_name='Content completed')),
                ('average_rating', models.FloatField(default=0, verbose_name='Average rating')),
                ('review_number', models.IntegerField(default=0, verbose_name='Number of reviews')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='list',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
