# Generated by Django 4.0.5 on 2022-06-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_alter_list_user_fk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
