# Generated by Django 4.0.5 on 2022-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ratingmovietv'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='content_id',
            field=models.IntegerField(default=1, verbose_name='Content id'),
            preserve_default=False,
        ),
    ]
