# Generated by Django 4.0.5 on 2022-07-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_progress_content_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('content_id', models.IntegerField(verbose_name='Content id')),
                ('content_type', models.CharField(max_length=10, verbose_name='Content type')),
                ('list_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list')),
            ],
            options={
                'verbose_name': 'List content',
                'verbose_name_plural': 'List contents',
            },
        ),
    ]
