# Generated by Django 4.0.5 on 2022-07-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_listcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_watched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
