# Generated by Django 4.0.5 on 2022-07-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_progress_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
    ]
