# Generated by Django 4.0.5 on 2022-07-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
